language: php

sudo: false

php:
  - 5.5
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

script:
  - composer validate
