language: php

sudo: false

env:
  global:
    secure: "byDwzM186eqc63os2zogfBPcwJ5qB/vjbTvDQIU0oUQBrFAWA8s9jyNJ8fxGs4BqDO74C2cxSIXniV7im1r7fbh9U78tRwQDefXgzvdklYGhBMqnYNtWwyvnArdvyajGqTJgady/etDMYRP4otY+qVZ31Jig3A/nBrnpdoiVs9suuOXl9QSm2bzkn+KpC5fQHeUCy8s3keEjoPijVk9aMB9PpknI68rFwBzNZXT2gFLiPYJfOsiz7LlSbDDDrgaY4gSUQtjfFOMMNgzcVW5E8eT+YtoZJFkzC1UxUqzCWgrMzETd/2w4GV6Xq9hn/eGl1RyjnoiFfudd7Bue1CPX8gsZAWXBvWQ7j3jCWdWD0z1Se2YLNVMrc8/O50OV814oUvYr2YvelYGb7VfAETa8t27Ah0a4m+IWN3oXIOcc7vk66FzIxrbtCW8WG+0m6BTVJoOOCjFtrKhFFwWPRHn4EV6JmIRoy3UOA8cZ/pG8uuqrgXTWzuY01p7Il3yndm95RYUtRggyJXBMnn9CrrKN039s17tXX0NnswOjwWVLKpS5YX/pSNz3LN1fqK+MYoPzjivjotF0QxBp+vHW/SxO4RLuAv4ffWj/WZUG9qjGgDt3KNnFC7b1LKJGSyN1kYfT2qu8praDRBWDemWuKi4M8OMtkYU6QkLYclxMD9i8X3c="

addons:
  code_climate:
    repo_token:
      secure: "BFgmYwkXAFl/F0uPjU2TM3sG6QirKZszEivyrxhZ3XCFP1n/T/qpyn3Al1lEkL0D7R8X3+YFCx+440A4Q5/z9hGnzsMTzryesrOlZ/dvXemysYsKW6B+qLmEaSAeW5RirjtT9dYe4ycYtK9MITUQ/1ZwDj7zqpgESwTmYbzg/8Y2CIQPX71dC+i9ppSUHkLnjjqurRNwtjInz9RdCvMsza6aQlwjl89gCuDD2H3/pdnpTNnaWqcLOeN4WpdWj/MhKHbj/6IEcf+ybVoGVCqtwSJSEr32JJV+1mIZ0XhZo61jrGcrdKwuEmfUoHnBf1V05P3+uLQsQ3JEkErgtIzPyYTA9Q2GIfQx4uOWkAitvhb89L2l8n23cxHYJUGcqEATg/NmoqX6Iai99d5uaB3lQyOVmrpyDhx9M+VMuDGLOqLuQTSg2UxPRuyOMnezVVMgburGHsU9kScXpCcwAOq2ja91rkcI/N3EklHuTocoiLEcVqGiR1GnOIgErXefLSeMc/DyBjdwyOV5iCSAn+8azQcTkqfj3r3/D4UeuYBTKTL79hzCARmIpTIMgPnpz618N90e3SUmKnejR22dbWkV4cFqD++puocgKEbEHlsp0ME1PXH+7qNKhIxW+sIAuTIIlQX8vf6Fmf9ejNM8sbxglNiZP1AiIW5WYt1lkHdp8mU="

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: COLLECT_COVERAGE=true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer config github-oauth.github.com $GITHUB_TOKEN
  - composer validate

install:
  - composer install --prefer-dist

before_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then IS_MERGE_TO_MASTER=true; fi

script:
  - if [[ "$COLLECT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/phpunit --configuration=phpunit.xml --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit --configuration=phpunit.xml; fi

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" && "$IS_MERGE_TO_MASTER" == "true" ]]; then vendor/bin/test-reporter --coverage-report build/logs/clover.xml; fi
